# Generated by Django 2.2.3 on 2019-07-12 06:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190710_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 12, 9, 11, 54, 629830), verbose_name='date published'),
        ),
    ]
