# Generated by Django 2.2.3 on 2019-07-12 06:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190712_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 12, 9, 27, 22, 326064), verbose_name='date published'),
        ),
    ]
