# Generated by Django 2.2.3 on 2019-07-12 06:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190712_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 12, 9, 35, 12, 919707), verbose_name='date published'),
        ),
    ]
